[programs.localnet]
atomic_lock = "GpE4KVAv1Pzc2uhACFU6dAcLac46995Ueh2bhrKngtrM"

[programs.devnet]
atomic_lock = "GpE4KVAv1Pzc2uhACFU6dAcLac46995Ueh2bhrKngtrM"
 
 [provider]
 cluster = "Localnet"
 wallet = "~/.config/solana/id.json"
 
 [registry]
 url = "https://api.apr.dev"
